### ISSUE TITLE
AltGr+I does not make ^

### ISSUE THREAD

**Issue by waneck** [adunning/Mac-Keyboard-Layouts-for-Windows#6]
On mac, Option+I will activate the dead key for `^`, used in places like `ê`. Both of the layouts provided here will instead generate `ʼ`, as in `ʼi`. Also, on Mac Option+c generates `ç` without the need of using a dead key for it.
Is there any reason for this? Is there any way to make it so the keyboard accents work the same as on mac?

Thank you!

**Comment by adunning** [comment]
It sounds as if you're using the US Extended/ABC Extended layout rather than the standard US layout; it's the latter of these that imitates the classic Mac layout.

**Comment by waneck** [comment]
You're right - `United States: Extended` is what appears when I install the layout - and that was what I installed at first. Since then, I uninstalled it and tried to install us-mac multiple times, but it always adds back the extended layout instead. Is there any files I should dig in to make sure that the extended keyboard layout is removed?

**Comment by adunning** [comment]
Perhaps check that you're running the actual uninstaller via Programs and Features, rather than just removing it from the keyboard options? It is actually possible to have both installed in parallel, but the interface in Windows can be quite confusing when multiple keyboard layouts are attached to the same language.

**Comment by waneck** [comment]
I see. Thank you - Actually rebooting my pc did the trick!

**Comment by adunning** [comment]
Glad that worked!
